import './globals.css'
import { rubik, chivo_mono } from '@/scripts/fonts'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${rubik.variable} ${chivo_mono.variable}`}>
      <body>
        {children}
      </body>
    </html>
  )
}
