import './globals.css'
import { Chivo_Mono, Lexend } from "next/font/google";

export const chivo_mono = Chivo_Mono({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-chivo-mono',
});

export const lexend = Lexend({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-lexend',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${lexend.variable} ${chivo_mono.variable}`}>
      <body>
        {children}
      </body>
    </html>
  )
}
